language: python
python: '3.5'
env:
  matrix:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=flake8
install:
- pip install tox
script:
- tox
matrix:
  fast_finish: true
before_install: pip install codecov
after_success: codecov
